### ISSUE TITLE
[doc] URL about Resources on Acceleo web page are out-dated

### ISSUE THREAD

**Issue by ejuliot** [eclipse-acceleo/acceleo#109]
At https://eclipse.dev/acceleo/support.html, Community Support has a link to bugzilla, It should now refer to https://github.com/eclipse-acceleo/acceleo/issues

At https://eclipse.dev/acceleo/resources.html , the link "git" refers to http://git.eclipse.org/c/acceleo/org.eclipse.acceleo.git/ , and there is also the old gerrit link. They have to be updated to https://github.com/eclipse-acceleo/acceleo

The footer is also outdated.

At https://eclipse.dev/acceleo/resources.html, the first link of the documentation is http://help.eclipse.org/photon/index.jsp?topic=/org.eclipse.acceleo.doc/pages/index.html  (photon is outdated) which hopefully itself redirect to https://help.eclipse.org/latest/index.jsp?topic=/org.eclipse.acceleo.doc/pages/index.html  

At https://projects.eclipse.org/projects/modeling.m2t.acceleo, the documentation tab on the right side refers to AQL documentation, not the Acceleo documentation. The getting start refers to http://wiki.eclipse.org/Acceleo instead of https://wiki.eclipse.org/Acceleo/Getting_Started . The official web page is still eclipse.org/acceleo instead of eclipse.dev

The https://github.com/eclipse-acceleo/acceleo/README should have a link to the Acceleo web site https://eclipse.dev/acceleo/

**Comment by ylussaud** [comment]
see [this issue](https://github.com/eclipse-acceleo/acceleo-website/issues/1).
