### ISSUE TITLE
A wrong classpath is computed when using Acceleo with Spring Sts 4.22

### ISSUE THREAD

**Issue by ylussaud** [eclipse-acceleo/acceleo#154]
Spring Sts 4.22:
Version: 4.22.0.RELEASE
Build Id: 202403071427
Revision: 44291b464093d161f115d8e16059e5272ed3c8

The folder of the project is added to the classpath which lead to resolving qualified names starting with `bin::` and `src::`.
Manually changing the output folder in the Java settings of the project seems to fix this behavior.

**Comment by cbrun** [comment]
I have the same unexpected behavior with the [Eclipse IDE for Eclipse Committers](https://www.eclipse.org/downloads/packages/release/2024-06/r/eclipse-ide-eclipse-committers)

**Comment by ylussaud** [comment]
I added an optional dependency to the AQL JDT integration feature. This should automatically add needed plugins whenever the optional feature can be installed (see 2911281598abe29fa62d5db2a3242bf7c9863bf4).
