### ISSUE TITLE
Conditional's predicate must evaluate to a boolean value but was [true]

### ISSUE THREAD

**Issue by erichstuder** [eclipse-acceleo/acceleo#156]
Hello

I have a strange behavior which I just can't understand.

I have this short template.
It works fine except for the if statement.

```
[template` private generate_class_header(class : uml::Class)]
  [file (class.name + '.h', overwrite, 'UTF-8')]
    #pragma once

    [for (dependency | class.clientDependency)]
      [if (dependency.supplier.eContainer(uml::Package).name.toString().startsWith('E'))]
        ['#include <' + dependency.supplier.name + '.h>\n'/]
      [else]
        ['#include "' + dependency.supplier.name + '.h"\n'/]
      [/if]
    [/for]
[/template]
```

The editor gives an error:

> The predicate never evaluates to a boolean type ([Sequence(java.lang.Boolean)]).

When I run the script i get the errors:

> ERROR generate L44: The expression must be evaluated to a boolean not: false
> ERROR generate L44: The expression must be evaluated to a boolean not: true
> WARNING generate L52: AQL evaluation issue
> 	WARNING generate L52: Conditional's predicate must evaluate to a boolean value but was [true] instead.

Why does the if never evaluate to a boolean?
The documentation of startsWith states:

> Returns true if the current String starts with the string "b".

I have no clue how to understand this:

> ...must evaluate to a boolean value but was [true]...

But, if I put out the predicate just as a line it outputs true or false into the generated files as expected.
What am I getting wrong here? Or could this be a bug?

**Comment by erichstuder** [comment]
just found out it is a sequence that is returned and using ->at(1) solved my problem

never mind

**Comment by ylussaud** [comment]
Yes the returned value isn't a scalar and not a boolean but a collection of boolean. As you might have notices we still have some issues with the Acceleo 4 launch configuration. At the moment please generated and use the main Java class.
