### ISSUE TITLE
Add a validation error when a bock is not indented by two spaces or tabulations.

### ISSUE THREAD

**Issue by ylussaud** [eclipse-acceleo/acceleo#157]
Add a validation error when a bock is not indented by two spaces or tabulations.

**Comment by ylussaud** [comment]
IMO this lead to readability issue, in the following example it's important to add the `*` for readability and maintenance even if it wont be generated:
![image](https://github.com/user-attachments/assets/24e75e94-1844-4319-9014-f904f6e1d11d)

**Comment by ejuliot** [comment]
I fully disagree. 
In this screenshot, it is really hard to understand if the * will be generated or not. I consider the error really valuable and the template should remove the * to keep the template easy to read.

**Comment by ejuliot** [comment]
Just to avoid any misunderstand: my last comment was about the issue raised by the screenshot, not about the value of the validation error.
In other words, from my point of view, I think the error shown in screenshot are really useful. 

Another argument: in this example, it is very hard to know if *     [r.getComParamIdIn()/]  will be generated with a prefix with *{1 space}  or *{5 spaces}. I suppose it will be with 1 space, and so, the template become hard to understand.

Even the screenshot of "White Space" section of the official documentation at https://github.com/eclipse-acceleo/acceleo/blob/master/plugins/org.eclipse.acceleo.aql.doc/pages/language.adoc  shows an example with "some text" with only spaces as prefix, while the generated text is prefix by "-" as it was prefixing the [for] statement.

**Comment by ylussaud** [comment]
Just to have all information:
```
     /**
      * Constructeur complet du dto '[d.nameClassDto()/]'.
      * @param [d.nameENUM_PK_ID().apply_parameterMethodClassicIn()/]
      *           (In)(*) L'identifiant de [d.nameBaseDto()/].
      * [for (a : environment::Attribute | d.attributesNotComputed())]
          [a.getComParamIn()/]
        [/for]
      * [for (r : environment::Reference | d.referencesNoStar())]
          [if (not r.referencedType.oclAsType(environment::DTO).isNotPersistent())]
            [r.getComParamIdIn()/]
          [/if]
        [/for]
      * [for (r : environment::Reference | d.referencingStar())]
          [r.getComParamInverseIdIn()/]
        [/for]
```
and
```
     /**
      * Constructeur complet du dto '[d.nameClassDto()/]'.
      * @param [d.nameENUM_PK_ID().apply_parameterMethodClassicIn()/]
      *           (In)(*) L'identifiant de [d.nameBaseDto()/].
      * [for (a : environment::Attribute | d.attributesNotComputed())]
      *   [a.getComParamIn()/]
      * [/for]
      * [for (r : environment::Reference | d.referencesNoStar())]
      *   [if (not r.referencedType.oclAsType(environment::DTO).isNotPersistent())]
      *     [r.getComParamIdIn()/]
      *   [/if]
      * [/for]
      * [for (r : environment::Reference | d.referencingStar())]
      *   [r.getComParamInverseIdIn()/]
      * [/for]
```
would both generate something like:
```
   /**
    * Constructeur complet du dto 'Author'.
    * @param id
    *           (In)(*) L'identifiant de author.
    * @param name
    *           (In)(*) name.
    */
```
The question is should we forbid users to write the second forme ?
Also this check slow down validation by more than 17%.

**Comment by vrichard12** [comment]
Hi,

I think that introducing the capacity of ingoring text will confuse some users. The rigor that Acceleo 4 brings to the management of line breaks is very noteworthy. Introducing the ability to ignore text goes against this rigour.
A new paragraph with illustrations will be needed in the documentation to explain this case, which I feel adds unnecessary complexity.
Case 1 looks much clearer to me. Maybe case 2 is nicer to look at, but that shouldn't be the concern of a developer. Things have to be clear and unambigous. In case 1 we don't have to think about which static text is going to be generated or ignored, it is simpler to understand.
I understand that it impacts performance, but I think it is justified.

**Comment by ylussaud** [comment]
OK I though it would be easier to look for a big block of Java doc in the module when one want to modify the generated Java doc. But I'll apply the patch. I'll have a look at the code but I don't think  I'll be able to improve performance.

**Comment by cbrun** [comment]
Hi, chiming here for a bit.

I agree that not informing the user when static text in a template doesn't produce any output is problematic. It makes it extremely difficult to understand how the template is functioning and why it's not generating the expected results.

That said, perhaps we can address this issue differently instead of treating it as a validation error. What if we visually highlight these "ignored areas" by applying a specific background color to the text? Would that be technically feasible to implement or is that not really covered by the LSP mechanisms ?

**Comment by ylussaud** [comment]
I already have a patch to handle this case as a parsing error. Maybe we could add a background color on top of that in the editor. But Acceleo use the generic editor, so I need to check if it can be done. The styling is handled by text mate which only use regular expressions which can be an issue to style composite blocks.

**Comment by cbrun** [comment]
Thanks for your feedback, the consensus seems to be that the parsing error is fine so let's keep the alternative aside if the need arise.
