### ISSUE TITLE
Where can I find p2 update site binary package of 3.7.12 ?

### ISSUE THREAD

**Issue by MrXiaoFan** [eclipse-acceleo/acceleo#20]

**Comment by Kellindil** [comment]
Hello,

3.7.12 is available as an update site from either https://download.eclipse.org/acceleo/updates/releases/3.7/ or https://download.eclipse.org/acceleo/updates/releases/3.7/R202211151354/ .
You can find a zip of this update site at https://download.eclipse.org/acceleo/downloads/drops/3.7.12/R202211151354/ .

Laurent Goubet
Obeo
