### ISSUE TITLE
Open declaration on template parameter reference opens the template in the java output folder (bin)

### ISSUE THREAD

**Issue by ylussaud** [eclipse-acceleo/acceleo#28]
Opening a module `/test/src/test/otherModule.mtl` and opening the declaration:

    [template public generateParameter(eParam : ecore::EParameter) post(self.trim())]
      [ePa<here>ram.name/] : [eParam.eType.name/]
    [/template]

Opens the declaration but in the bin folder `/test/bin/test/otherModule.mtl`.

see/use IQualifiedNameResolver.getSourceLocation()

This lead to the following exception:

```
Caused by: java.lang.IllegalStateException: Could not find the Acceleo Text Document at URI file:///home/development/bin/eclipse-2019-12-Acceleo-query/runtime-New_configuration/test/bin/test/otherModule.mtl
	at org.eclipse.acceleo.aql.ls.services.textdocument.AcceleoTextDocumentService.didOpen(AcceleoTextDocumentService.java:112)
	... 16 more
```

```
Caused by: org.eclipse.acceleo.aql.ls.services.exceptions.LanguageServerProtocolException: Received a notification for document "file:///home/development/bin/eclipse-2019-12-Acceleo-query/runtime-New_configuration/test/bin/test/otherModule.mtl" but it has not previously been opened. This should never happen.
	at org.eclipse.acceleo.aql.ls.services.textdocument.AcceleoTextDocumentService.checkDocumentIsOpened(AcceleoTextDocumentService.java:222)
	at org.eclipse.acceleo.aql.ls.services.textdocument.AcceleoTextDocumentService.documentSymbol(AcceleoTextDocumentService.java:362)
	... 16 more
```

**Comment by ylussaud** [comment]
This behavior is not present in the RCPTT product and might be only present when launching a runtime.

**Comment by ylussaud** [comment]
This happen also in the pacman environment:
* open pacman-acceleo4/fr.pacman.start/src/fr/pacman/start/generateStart.mtl
* open declaration of `getRootConfig(true)` line 15

**Comment by ylussaud** [comment]
This was related to the packaging of the plugin.

**Comment by achimwackerow** [comment]
I'm seeing what looks like the same exception signature, but with a
different triggering scenario — worth noting in case the original
fix for this issue only addressed the bin-vs-src path cause.

Environment: Eclipse 2025-06 (Modeling), Acceleo 4.2.2
(R202603201315), lsp4j 1.0.0.v20260209-1721.
Java: 21.0.7 (Eclipse Adoptium / JustJ)
OS: Ubuntu Linux, x86_64
This is a fresh install of Eclipse and Acceleo after experiencing similar issues with Eclipse 2026-06 (Modeling), Acceleo 4.2.2

In my case the failing URI is already a *source* path (not `bin`):

  file:///.../bundles/ucmism2t.core/src/ucmism2t/queries/packageQuery.mtl

Trigger: a `.mtl` file (`packageQuery.mtl`) that is imported by other
modules, but has not yet been opened in any editor tab, gets a
server-initiated `didOpen` (e.g. triggered by validating an importing
module during workspace synchronization). That didOpen itself throws:

  java.lang.IllegalStateException: Could not find the Acceleo Text
  Document at URI file://.../packageQuery.mtl
      at AcceleoTextDocumentService.didOpen(AcceleoTextDocumentService.java:146)

This issue might be related:
The IDE editor has a mark with the message: Couldn't find the 'u_modelNamedElementByName(EClassifier=Model,java.lang.String)' service. But the actual call gives u_modelNamedElementByName a uml::Model which is expected. The IDE marks now many query calls as unresolved which worked before. I’m not sure how I’m supposed to carry on with this work under these circumstances.

It is a migration work from Acceleo 3.7 which is almost completed. The project has 143 queries and 183 templates. See: https://github.com/uml-subset/ucmism2t.

A restart of Eclipse results in: An internal error occurred during: "Synchronizing AcceleoWorkspace[file:/home/wackerow/eclipse-workspace/eclipse-modeling-2025-06-R-linux-gtk-x86_64_acceleo4-2-R202603201315]".
org/eclipse/uml2/uml/Model

The terminal window reports:
CompileCommand: exclude org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.getExtendedRange bool exclude = true
Jun 25, 2026 4:39:46 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
Warning: NLS missing message: MarketplacePage_favorites in: org.eclipse.epp.internal.mpc.ui.wizards.messages
Jun 25, 2026 4:46:31 PM org.eclipse.tm4e.core.registry.Registry _doLoadSingleGrammar
WARNING: No grammar source for scope [source.glsl]
Jun 25, 2026 4:46:31 PM org.eclipse.tm4e.core.registry.Registry _doLoadSingleGrammar

A 3rd restart was successful but the same happened as described above:
org.eclipse.acceleo.aql.ls.services.exceptions.LanguageServerProtocolException: Received a notification for document "file:///media/wackerow/Shared/Git/github/ucmism2t/bundles/ucmism2t.core/src/ucmism2t/queries/packageQuery.mtl" but it has not previously been opened. This should never happen.
The IDE marks now many query calls as unresolved which worked before.
