### ISSUE TITLE
AQL feature completion does not work on dynamic meta-models

### ISSUE THREAD

**Issue by pcdavid** [eclipse-acceleo/acceleo#54]
I have a dynamic metamodel (no generated Java code, just the `EPackage` created in memory), say `pkg`.
Inside of it, I have an `EClass` name `A` with an `EAttribute` `name: EString`.

I try to complete the expression `self.`, with a setup like this:

```java
IQueryCompletionEngine engine = QueryCompletion.newEngine(this.queryEnvironment);
Map<String, Set<IType>> variableTypes = new LinkedHashMap<>();
final Set<IType> potentialTypes = new LinkedHashSet<>(1);
potentialTypes.add(new EClassifierType(this.queryEnvironment, selfType));
variableTypes.put("self", potentialTypes);
return engine.getCompletion(expression, offset, variableTypes);
```
where `selfType` is my EClass `A`. The parent EPackage is correctly registered in the `queryEnvironment`.

I expect `engine.getCompletion()` to return a completion proposal for `self.name`, but it returns nothing.

After digging into the code and discussing with @ylussaud, here is what seems to happen:

1. We end up (correctly) in `BasicLookupEngine.getServices(Set<IType>)` with the correct values.
2. This code tries to find the service(s) for which `service.getParameterTypes(queryEnvironment).get(0).isAssignableFrom(type)` is `true`.
3. Inside the set of known services, we have an instance of `EObjectServices.EObjectFeatureAccess`, which is the one that should normally handle this.
4. Calling `service.getParameterTypes(queryEnvironment).get(0)` on it returns a `ClassType` representing `org.eclipse.emf.ecore.EObject`.
5. `ClassType.isAssignableFrom(IType)` only works for types which exist as Java classes, i.e. for metamodels with generated code.

At step 4, calling `service.getParameterTypes(queryEnvironment)` on `EObjectFeatureAccess` invokes the implementation of `getParameterTypes` from `JavaMethodService.getParameterTypes(IReadOnlyQueryEnvironment)`, which only returns `IJavaType`s.

Not sure if `EObjectFeatureAccess` should override `getParameterTypes` or if `JavaMethodService.getParameterTypes` itself should be updated, but if a type (here `EObject`) is actually an `EClassifier`, it should return an `EClassifierType` instead of a `ClassType`. `EClassifierType.isAssignableFrom()` uses the reflexive EMF APIs and should work correctly on dynamic metamodels.

**Comment by ylussaud** [comment]
We want to make sure instances passed to `JavaMethodService` compatible a a ClassType to make sure we don't have any issue at runtime. I think it's better to add a dynamic `EObject` case in `AbstractJavaType.isAssignableFrom()`.
